### ISSUE TITLE
Migrate from RethinkDB to Postgres

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#30]
## Phase III: Bug chasing
 - [ ] Invite logic needs updating in knex #86
 - [ ] assignments assigning, but making a second campaign seems to have weird behavior (thinks it already contacted the same contacts)
 - [x] message.service is not being set properly

## Phase II:
(checked means merged into master or `knex` branch)

 - [x] `workers/(incoming-|message-sender-)*.js`: .group()...
       work requires coordination with moving away from user_number paradigm
       For similar pattern without regex, try `.where(field, 'LIKE', '%7').orWhere..`
 - [x] #74  `workers/jobs.js::assignTexters(job)`: .merge with meta/sub-queries
 - [x] `server/notifications.js`: .changes() 
       Might be able to implement this in rethink-knex-adapter as a listener
 - [x] `workers/number-assigner.js` does-not-equal pattern in filter().  Also might want to try supporting relative `ne`, `gt`, etc in rethink-knex-adapter
 - [x] [pr](https://github.com/MoveOnOrg/rethink-knex-adapter/pull/7) `api/schema.js::joinOrganization`: `nth()` (rethink-knex candidate) @schuyler1d
 - [x] #74 `api/schema.js::createOptOut`: merge(), ?forEach()? (or is that on a returned val)
 - [x] #74 `api/schema.js::sendMessage`: merge()
 - [x] #74  `api/schema.js::deleteQuestionResponses`:  complex filter()
 - [x] `api/campaign-contact.js`: innerJoin (on top of another eqJoin)
 - [x] #70  `api/user.js::todos`: complex filter with `r.and(...)` @schuyler1d

## Phase I:
 - [x] Migrate away from all `type.object()` and `type.array()` schemas
 - [x] [rethink-knex-adapter](https://github.com/MoveOnOrg/rethink-knex-adapter#currently-supported-query-methods) 80% support

**Comment by schuyler1d** [comment]
closing this issue, since have now merged `knex` branch.  bug fixing should be on new issues.
:fireworks:
