### ISSUE TITLE
Twilio error code handling for optout and admin visibility

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#451]
This is a meta-issue (or, go ahead fix it all), gathering twilio error codes we should handle and either:
1. opt-out the contact (possibly with a disposition/log of why)
2. expose to the admin for further debugging/awareness of an issue

## Opt out error codes
 - [ ]  handset issue (#316) (30005 Unknown destination handset )
 - [ ] landline or unreachable number https://www.twilio.com/docs/api/errors/30006
 - [ ] texted STOP - https://www.twilio.com/docs/api/errors/21610
 - [ ] Unreachable destination handset https://www.twilio.com/docs/api/errors/30003

## Expose to superadmin
 - [ ] Account Suspended https://www.twilio.com/docs/api/errors/30002
 - [ ] Queue overflow https://www.twilio.com/docs/api/errors/30001
 - [ ] The Messaging Service contains no phone numbers https://www.twilio.com/docs/api/errors/21704
 - [ ] The Messaging Service is invalid  https://www.twilio.com/docs/api/errors/21705

And maybe there should be a superadmin interface just to see a report on error codes

**Comment by ibrand** [comment]
@schuyler1d with the error code work merged in, is any of this handled?

**Comment by schuyler1d** [comment]
No, but it's now a much more discrete feature we can aim for -- I'm hoping to add a graph/pie-chart on the campaign reporting page.  Maybe we should also have an org-report page.....

**Comment by ibrand** [comment]
This is ready for someone to start looking at. At this point, we have logging of twilio error codes. This would be a task of creating charts from that data

**Comment by ibrand** [comment]
I want to add a bullet to this issue for error code metrics at the campaign level and error code metric reports at the org (and cross-org level) for the `30007 - Carrier Violation` as outlined in this comment: https://github.com/MoveOnOrg/Spoke/issues/1552#issuecomment-629493627

More context on that issue (#1552)

**Comment by schuyler1d** [comment]
Campaign stats gained this in Spoke 6.19/7.0.  The second piece could be done with experimental Message Handlers framework introduced in the same version (and extended in upcoming 7.1)

**Comment by Frydafly** [comment]
@schuyler1d following up since now a lot of this is exposed to admins in the UI. 

Linking to https://github.com/MoveOnOrg/Spoke/issues/316 which I think is a sub-issue of this. The issue requests a way to check for wrong numbers before sending. 

Is it possible to add a message handler that checks whether a phone number connected to an outgoing text has previously been flagged as a landline or wrong number by twilio/messaging service? @lperson

**Comment by schuyler1d** [comment]
Actually, I think this is completed because errors are reported to admins in the Campaign Stats page and we have a message handler for opt-out (text based).  I think #316 we can keep open/separate and, indeed, there could be a message handler which chooses to *optout* e.g. unknown handsets -- we don't have one of those yet but maybe worth waiting for Twilio refactor for that kind of thing.
