### ISSUE TITLE
Scaling meta-issue

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#487]
Scaling goals:
* 2000+ simultaneous texters
* 1million+ messages/day
* Bigger lists loaded in contacts - without getting stuck/slow

This issue is meant to track/discuss ideas around scaling. Please refer to it in relevant pull-requests and issues.

Some categories to consider:
* Redis/Caching intermediate layer for texter-bottlenecked apis (#254)
* Finding performance bottlenecks, in general
* Client-side performance wins
* Performance testing

**Comment by shakalee14** [comment]
We think this can happen in 9 steps --> "smaller" PRs vs 1 big PR
- [ ] Add/install `connect-redis` and `fakeredis` for production and dev  
- [ ]  Implementing Campaign ORM structure. Implement it in easy spots - so for example, accessRequired / access control. This way we can prove that this concept works and is self contained.
- [ ]  Then stub out ORM 
- [ ] Move database calls into the ORM
- [ ] Implementing what happens in the start campaign (write)--> when you create a campaign it'll make a bunch of key value pairs to represent that campaign
- [ ] Mutation writes - instead of db, write to redis
- [ ] Create background process that syncs redis writes to db
- [ ] Fill out reads
- [ ] Monitor sql when debugger is on - using some knex debugging features to make sure sql calls happen - this way we make sure we aren't actually touching the DB
