### ISSUE TITLE
enhance AdminIncomingMessage view

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#546]
# Make it filterable

- [x] Incoming messages that have not been responded to.
- [x] All messages for a campaign.
- [x] All messages for a campaign that have not been responded to.
- [x] All messages.

Implement this with extensibility in mind (to filter for other things, such as profanity).

# Make the messages actionable

- Commandeer selected message(s), which will assign them to the current admin user

Implement this with extensibility in mind.

# Notes

This work is a prerequisite for #359.

This work will involve removing the /allmessages endpoint and replacing it with a graphql root query.

**Comment by ben-pr-p** [comment]
It'd be great if this also included (as display and filter options): assignee, timestamp, and time since response – 

Then our review workflow could be filter by unresponded, sort by time since response, and work through it

**Comment by lperson** [comment]
@ben-pr-p When you say "work through it" are you ok with the concept of commandeering for the current user?  Thinking about it, would reassign to any user be better?

**Comment by ben-pr-p** [comment]
I think reassign to any user is best! It encompasses commandeering so :+1:

**Comment by joemcl** [comment]
@lperson @ibrand @deasterdaywfp @suegibson @bchrobot @ben-pr-p - I think the work @lperson has done on Message Review accomplishes all the goals laid out here, though I can't tell (with my limited coding skillz) if this was accomplished - "Implement this with extensibility in mind (to filter for other things, such as profanity)". Thoughts?

**Comment by ibrand** [comment]
@lperson what do you think? Does this feel done and encompassed by message review?

**Comment by suegibson** [comment]
Not sure I am understanding, but I would NEVER “reassign to any user”, only to a specific texter.

**Comment by lperson** [comment]
@ibrand This is evolving largely due to ongoing input from @suegibson.  Unfortunately the most recent iterations currently live in the WFP fork.  The[ WFP parity project](https://github.com/MoveOnOrg/Spoke/projects/14) includes several pieces of work related to this.

@suegibson I think "reassign to any user" means "reassign to any user *YOU CHOOSE.*

@joemcl yes, it's sort of designed with extensibility in mind.  Tagging and filtering by tag in message review would move us in that direction.

**Comment by ibrand** [comment]
Ok! Nice that's helpful. I'm labeling it as `C-meta` for now since it encompasses a lot of sub-changes

**Comment by Frydafly** [comment]
Checking in @lperson since this seems to be largely accomplished! Though I can't know for sure, I also have limited code skilz

cc @schuyler1d

**Comment by schuyler1d** [comment]
Yes, all of these are in main
