### ISSUE TITLE
Scaling architecture meta-issues

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#860]
The scaling proposal at
https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO-scale-spoke-plan.md
is a good start, but as we begin implementation we will come up with questions/issues that are not yet addressed/thought-through.

This is meant to track those:
 - [ ] optouts: [PR](https://github.com/MoveOnOrg/Spoke/pull/832/files)
 - [ ] assignment lookup: Currently TexterTodo looks up data through assignmentId but we don't key anything off of assignmentId.
   - use case: assignmentRequired: sometimes used during contact lookup/action tests -- if contact includes assigned user, we can skip that.
   - use case: assignmentRequired in getAssignmentContacts
   - use case: TexterTodoList: get assignments in org with current counts
   - use case: clear/update assignments when campaign is edited
 - [ ] contact.cell vs. contact.id: The proposal tracks cell, which is useful from the incomingMessage/twilio use-case, but the frontend/backend APIs from the texter all send campaignContactId
    - advantage to campaignContactId is unique to organization and campaign, while the cell can be confused across those. However, incomingMessage still won't have that, so the question is how to bridge incomingMessages, counting needs, and lookup
    - one option might be to change the API and send both cell and contactId in the frontend APIs
 - [ ] polling getContactIds and pushing/popping from a doesn't seem to match perfectly with texter api workflow.  may need to address this
